### PR TITLE
Trying to get property of non-object line 143

### PR DESCRIPTION
**Pull request by filipposarzana**
$ip_found is an array and should be used as is $ip_found['whitelisted']

### CODE REVIEW

**Comment by antonioribeiro** [comment]
Not sure how that did happen, but here it's not an array: http://i.imgur.com/QlCajha.png

**Comment by filipposarzana** [comment]
It's happening when launching command from terminal only once there'
already an ip address in db

_
Filippo Sarzana
http://avionerd.com
 +39 3661730904

On 09/mar/2015, at 18:44, Antonio Carlos Ribeiro <notifications@github.com>
wrote:

Not sure how that did happen, but here it's not an array:
http://i.imgur.com/QlCajha.png

—
Reply to this email directly or view it on GitHub
<https://github.com/antonioribeiro/firewall/pull/22#issuecomment-77904464>.

**Comment by antonioribeiro** [comment]
Is this Laravel 4? Not happeing in Laravel 5, tried the three possible results of $ip_found:

1) IP in database and Array
2) Country
3) Range

**Comment by antonioribeiro** [comment]
@filipposarzana Are you using a different model?

```
'firewall_model' => 'PragmaRX\Firewall\Vendor\Laravel\Models\Firewall',
```

**Comment by antonioribeiro** [comment]
Maybe your cache is returning an array in the next requests to the same IP?

But I think I'll merge it, because Eloquent implements ArrayAccess and it should work too.

**Pull request merged**
